=== jaggy163/SimpleChat/data/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/lol"
        xmlns:tns="http://www.example.com/lol"
        elementFormDefault="qualified">


    <element name="students">
        <complexType>
            <sequence>
                <element ref="tns:person"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <simpleType name="Login">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}"/>
        </restriction>
    </simpleType>
    <complexType name="Address">
        <sequence>
            <element name="country" type="string" />
            <element name="city" type="string" />
            <element name="street" type="string" />
        </sequence>
    </complexType>
    <complexType name="PersonType">
        <sequence>
            <element name="name" type="string" />
            <element name="telephone" type="positiveInteger" />
            <element name="address" type="tns:Address" />
        </sequence>
    </complexType>
    <complexType name="Student">
        <complexContent>
            <extension base="tns:PersonType">
                <attribute name="Login" type="tns:Login" use="required" />
                <attribute name="faculty" use="optional" default="mmf">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="mmf"></enumeration>
                            <enumeration value="geo"></enumeration>
                            <enumeration value="ksis"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Abiturient">
        <complexContent>
            <extension base="tns:PersonType">
                <sequence>
                    <element name="average-mark" type="double" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="person" type="tns:PersonType" abstract="true"></element>
    <element name="student" type="tns:Student" substitutionGroup="tns:person"></element>
    <element name="abiturient" type="tns:Abiturient" substitutionGroup="tns:person"></element>
</schema>

=== jaggy163/SimpleChat/data/students.xml
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/lol"
          xsi:schemaLocation="http://example.com/lol person.xsd">
    <abiturient>
        <name>Petkevich</name>
        <telephone>2787474</telephone>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Slobodskaja 7</street>
        </address>
        <average-mark>9.0</average-mark>
    </abiturient>
    <student Login="MitarAlex7" faculty="mmf">
        <name>Mitar Alex</name>
        <telephone>2456474</telephone>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Kalinovsky 45</street>
        </address>
    </student>
    <student Login="Pashkin5" faculty="mmf">
        <name>Pashkin Alex</name>
        <telephone>3453789</telephone>
        <address>
            <country>Belarus</country>
            <city>Brest</city>
            <street>Knorina 56</street>
        </address>
    </student>
</students>
